export default [
  {
    _id: 'collection1',
    title: 'Top Sci-Fi Movies',
    author: ['user1'],
    movies: ['movie1', 'movie2', 'movie3'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection2',
    title: 'Favorite Comedies',
    author: ['user2'],
    movies: ['movie4', 'movie5'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection3',
    title: 'Best of 2023',
    author: ['user3'],
    movies: ['movie6', 'movie7', 'movie8', 'movie9'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection4',
    title: 'Classic Movies',
    author: ['user4'],
    movies: ['movie10', 'movie1', 'movie2'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection5',
    title: 'Action-Packed Films',
    author: ['user5'],
    movies: ['movie3', 'movie4', 'movie5'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection6',
    title: 'Oscar Winners',
    author: ['user6'],
    movies: ['movie6', 'movie7'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection7',
    title: 'Underrated Gems',
    author: ['user7'],
    movies: ['movie8', 'movie9', 'movie10'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection8',
    title: 'Family Favorites',
    author: ['user8'],
    movies: ['movie1', 'movie3', 'movie5'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection9',
    title: 'Horror Films',
    author: ['user9'],
    movies: ['movie2', 'movie4', 'movie6'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection10',
    title: 'Romantic Movies',
    author: ['user10'],
    movies: ['movie7', 'movie8', 'movie9'],
    created: new Date('2023-09-22'),
  },
];
