export default [
  {
    _id: 'collection1',
    title: 'Top Sci-Fi Movies',
    titleId: 'top-sci-fi-movies',
    author: 'nanabanana',
    movies: ['movie1', 'movie2', 'movie3'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection2',
    title: 'Favorite Comedies',
    titleId: 'favorite-comedies',
    author: 'moviebuff99',
    movies: ['movie4', 'movie5'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection3',
    title: 'Best of 2023',
    titleId: 'best-of-2023',
    author: 'cinemalover',
    movies: ['movie6', 'movie7', 'movie8', 'movie9'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection4',
    title: 'Classic Movies',
    titleId: 'classic-movies',
    author: 'adminuser',
    movies: ['movie10', 'movie1', 'movie2'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection5',
    title: 'Action-Packed Films',
    titleId: 'action-packed-films',
    author: 'moviemaniac',
    movies: ['movie3', 'movie4', 'movie5'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection6',
    title: 'Oscar Winners',
    titleId: 'oscar-winners',
    author: 'filmcritic',
    movies: ['movie6', 'movie7'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection7',
    title: 'Underrated Gems',
    titleId: 'underrated-gems',
    author: 'cinephile',
    movies: ['movie8', 'movie9', 'movie10'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection8',
    title: 'Family Favorites',
    titleId: 'family-favorites',
    author: 'moviefanatic',
    movies: ['movie1', 'movie3', 'movie5'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection9',
    title: 'Horror Films',
    titleId: 'horror-films',
    author: 'superadmin',
    movies: ['movie2', 'movie4', 'movie6'],
    created: new Date('2023-09-22'),
  },
  {
    _id: 'collection10',
    title: 'Romantic Movies',
    titleId: 'romantic-movies',
    author: 'flickfan',
    movies: ['movie7', 'movie8', 'movie9'],
    created: new Date('2023-09-22'),
  },
];
