export default [
  {
    _id: 'comment1',
    postType: 'COMMENT',
    author: ['user1'],
    text: 'I really enjoyed this movie! The plot was captivating and the characters were well-developed.',
    created: new Date('2023-01-15'),
  },
  {
    _id: 'comment2',
    postType: 'COMMENT',
    author: ['user2'],
    text: 'The cinematography was stunning, but I felt the story lacked depth.',
    created: new Date('2023-02-20'),
  },
  {
    _id: 'comment3',
    postType: 'COMMENT',
    author: ['user3'],
    text: 'An absolute masterpiece! I would highly recommend it to anyone who loves thrillers.',
    created: new Date('2023-03-25'),
  },
  {
    _id: 'comment4',
    postType: 'COMMENT',
    author: ['user4'],
    text: 'This film had great potential, but it fell flat in the second half.',
    created: new Date('2023-04-30'),
  },
  {
    _id: 'comment5',
    postType: 'COMMENT',
    author: ['user5'],
    text: 'The acting was top-notch and the soundtrack was amazing. A must-watch!',
    created: new Date('2023-05-05'),
  },
  {
    _id: 'comment6',
    postType: 'COMMENT',
    author: ['user6'],
    text: 'A visually stunning movie with a powerful message. Truly inspiring.',
    created: new Date('2023-06-10'),
  },
  {
    _id: 'comment7',
    postType: 'COMMENT',
    author: ['user7'],
    text: 'I found the pacing to be a bit slow, but overall it was a decent film.',
    created: new Date('2023-07-15'),
  },
  {
    _id: 'comment8',
    postType: 'COMMENT',
    author: ['user8'],
    text: 'The plot twists were unexpected and kept me on the edge of my seat!',
    created: new Date('2023-08-20'),
  },
  {
    _id: 'comment9',
    postType: 'COMMENT',
    author: ['user9'],
    text: 'A well-crafted story with memorable characters. Definitely worth a watch.',
    created: new Date('2023-09-25'),
  },
  {
    _id: 'comment10',
    postType: 'COMMENT',
    author: ['user10'],
    text: 'Not my cup of tea. I found it quite boring and predictable.',
    created: new Date('2023-10-30'),
  },
];
