export default [
  {
    _id: 'discussion1',
    postType: 'DISCUSSION',
    movie: ['movie1'],
    title: 'The Best Movie Ever',
    text: 'This movie was absolutely amazing! The storyline, the characters, everything was perfect.',
    author: ['user1'],
    created: new Date('2023-01-15'),
    views: 100,
    comments: ['comment1', 'comment2'],
  },
  {
    _id: 'discussion2',
    postType: 'DISCUSSION',
    movie: ['movie2'],
    title: 'A Critical Review',
    text: 'While the visuals were stunning, the story lacked depth and the pacing was off.',
    author: ['user2'],
    created: new Date('2023-02-20'),
    views: 150,
    comments: ['comment3'],
  },
  {
    _id: 'discussion3',
    postType: 'DISCUSSION',
    movie: ['movie3'],
    title: 'Underrated Gem',
    text: 'This movie is highly underrated. It deserves much more recognition for its unique storyline.',
    author: ['user3'],
    created: new Date('2023-03-25'),
    views: 200,
    comments: ['comment4', 'comment5'],
  },
  {
    _id: 'discussion4',
    postType: 'DISCUSSION',
    movie: ['movie4'],
    title: 'Overhyped and Underwhelming',
    text: 'Despite all the hype, I found the movie to be quite underwhelming.',
    author: ['user4'],
    created: new Date('2023-04-30'),
    views: 300,
    comments: ['comment6'],
  },
  {
    _id: 'discussion5',
    postType: 'DISCUSSION',
    movie: ['movie5'],
    title: 'An Emotional Rollercoaster',
    text: 'This movie took me on an emotional rollercoaster. A must-watch!',
    author: ['user5'],
    created: new Date('2023-05-05'),
    views: 250,
    comments: ['comment7', 'comment8'],
  },
  {
    _id: 'discussion6',
    postType: 'DISCUSSION',
    movie: ['movie6'],
    title: 'A Visual Spectacle',
    text: 'The cinematography and special effects were out of this world.',
    author: ['user6'],
    created: new Date('2023-06-10'),
    views: 400,
    comments: ['comment9'],
  },
  {
    _id: 'discussion7',
    postType: 'DISCUSSION',
    movie: ['movie7'],
    title: 'Thought-Provoking and Deep',
    text: 'This movie left me thinking about its themes for days.',
    author: ['user7'],
    created: new Date('2023-07-15'),
    views: 180,
    comments: ['comment10'],
  },
  {
    _id: 'discussion8',
    postType: 'DISCUSSION',
    movie: ['movie8'],
    title: 'A Disappointing Sequel',
    text: 'The sequel failed to live up to the original.',
    author: ['user8'],
    created: new Date('2023-08-20'),
    views: 220,
    comments: [],
  },
  {
    _id: 'discussion9',
    postType: 'DISCUSSION',
    movie: ['movie9'],
    title: 'A Masterpiece of Storytelling',
    text: 'The storytelling in this movie was masterful and kept me engaged throughout.',
    author: ['user9'],
    created: new Date('2023-09-25'),
    views: 320,
    comments: [],
  },
  {
    _id: 'discussion10',
    postType: 'DISCUSSION',
    movie: ['movie10'],
    title: 'A Comedy Goldmine',
    text: 'I haven’t laughed this hard in a long time. Brilliant comedy!',
    author: ['user10'],
    created: new Date('2023-10-30'),
    views: 150,
    comments: [],
  },
];
