export default [
  {
    _id: 'movie1',
    title: 'Inception',
    director: 'Christopher Nolan',
    genre: 'Sci-Fi',
    release_date: new Date('2010-07-16'),
    rating: 8.8,
    poster: 'https://image.tmdb.org/t/p/w500/oYuLEt3zVCKq57qu2F8dT7NIa6f.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w780/s3TBrRGB1iav7gFOCNx3H31MoES.jpg',
    year: 2010,
  },
  {
    _id: 'movie2',
    title: 'The Matrix',
    director: 'Lana Wachowski, Lilly Wachowski',
    genre: 'Sci-Fi',
    release_date: new Date('1999-03-31'),
    rating: 8.7,
    poster: 'https://image.tmdb.org/t/p/w500/f89U3ADr1oiB1s9GkdPOEpXUk5H.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w780/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg',
    year: 1999,
  },
  {
    _id: 'movie3',
    title: 'The Shawshank Redemption',
    director: 'Frank Darabont',
    genre: 'Drama',
    release_date: new Date('1994-09-23'),
    rating: 9.3,
    poster: 'https://image.tmdb.org/t/p/w500/9cqNxx0GxF0bflZmeSMuL5tnGzr.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w780/iNh3BivHyg5sQRPP1KOkzguEX0H.jpg',
    year: 1994,
  },
  {
    _id: 'movie4',
    title: 'The Godfather',
    director: 'Francis Ford Coppola',
    genre: 'Crime',
    release_date: new Date('1972-03-24'),
    rating: 9.2,
    poster: 'https://image.tmdb.org/t/p/w500/3bhkrj58Vtu7enYsRolD1fZdja1.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w780/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg',
    year: 1972,
  },
  {
    _id: 'movie5',
    title: 'The Dark Knight',
    director: 'Christopher Nolan',
    genre: 'Action',
    release_date: new Date('2008-07-18'),
    rating: 9.0,
    poster: 'https://image.tmdb.org/t/p/w500/qJ2tW6WMUDux911r6m7haRef0WH.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w780/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg',
    year: 2008,
  },
  {
    _id: 'movie6',
    title: 'Pulp Fiction',
    director: 'Quentin Tarantino',
    genre: 'Crime',
    release_date: new Date('1994-10-14'),
    rating: 8.9,
    poster: 'https://image.tmdb.org/t/p/w500/d5iIlFn5s0ImszYzBPb8JPIfbXD.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w780/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg',
    year: 1994,
  },
  {
    _id: 'movie7',
    title: 'Fight Club',
    director: 'David Fincher',
    genre: 'Drama',
    release_date: new Date('1999-10-15'),
    rating: 8.8,
    poster: 'https://image.tmdb.org/t/p/w500/a26cQPRhJPX6GbWfQbvZdrrp9j9.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w780/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg',
    year: 1999,
  },
  {
    _id: 'movie8',
    title: 'Forrest Gump',
    director: 'Robert Zemeckis',
    genre: 'Drama',
    release_date: new Date('1994-07-06'),
    rating: 8.8,
    poster: 'https://image.tmdb.org/t/p/w500/saHP97rTPS5eLmrLQEcANmKrsFl.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w780/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg',
    year: 1994,
  },
  {
    _id: 'movie9',
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    director: 'Peter Jackson',
    genre: 'Fantasy',
    release_date: new Date('2001-12-19'),
    rating: 8.8,
    poster: 'https://image.tmdb.org/t/p/w500/6oom5QYQ2yQTMJIbnvbkBL9cHo6.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w780/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg',
    year: 2001,
  },
  {
    _id: 'movie10',
    title: 'Star Wars: Episode V - The Empire Strikes Back',
    director: 'Irvin Kershner',
    genre: 'Sci-Fi',
    release_date: new Date('1980-05-21'),
    rating: 8.7,
    poster: 'https://image.tmdb.org/t/p/w500/7BuH8itoSrLExs2YZSsM01Qk2no.jpg',
    backdrop: 'https://image.tmdb.org/t/p/w780/1Rr5SrvHxMXHu5RjKpaMba8VTzi.jpg',
    year: 1980,
  },
];
