export default [
  {
    _id: 'movie1',
    title: 'Inception',
    director: 'Christopher Nolan',
    genre: 'Sci-Fi',
    release_date: new Date('2010-07-16'),
    rating: 8.8,
  },
  {
    _id: 'movie2',
    title: 'The Matrix',
    director: 'Lana Wachowski, Lilly Wachowski',
    genre: 'Sci-Fi',
    release_date: new Date('1999-03-31'),
    rating: 8.7,
  },
  {
    _id: 'movie3',
    title: 'The Shawshank Redemption',
    director: 'Frank Darabont',
    genre: 'Drama',
    release_date: new Date('1994-09-23'),
    rating: 9.3,
  },
  {
    _id: 'movie4',
    title: 'The Godfather',
    director: 'Francis Ford Coppola',
    genre: 'Crime',
    release_date: new Date('1972-03-24'),
    rating: 9.2,
  },
  {
    _id: 'movie5',
    title: 'The Dark Knight',
    director: 'Christopher Nolan',
    genre: 'Action',
    release_date: new Date('2008-07-18'),
    rating: 9.0,
  },
  {
    _id: 'movie6',
    title: 'Pulp Fiction',
    director: 'Quentin Tarantino',
    genre: 'Crime',
    release_date: new Date('1994-10-14'),
    rating: 8.9,
  },
  {
    _id: 'movie7',
    title: 'Fight Club',
    director: 'David Fincher',
    genre: 'Drama',
    release_date: new Date('1999-10-15'),
    rating: 8.8,
  },
  {
    _id: 'movie8',
    title: 'Forrest Gump',
    director: 'Robert Zemeckis',
    genre: 'Drama',
    release_date: new Date('1994-07-06'),
    rating: 8.8,
  },
  {
    _id: 'movie9',
    title: 'The Lord of the Rings: The Fellowship of the Ring',
    director: 'Peter Jackson',
    genre: 'Fantasy',
    release_date: new Date('2001-12-19'),
    rating: 8.8,
  },
  {
    _id: 'movie10',
    title: 'Star Wars: Episode V - The Empire Strikes Back',
    director: 'Irvin Kershner',
    genre: 'Sci-Fi',
    release_date: new Date('1980-05-21'),
    rating: 8.7,
  },
];
