export default [
  {
    _id: 'profile1',
    user: ['user1'],
    profileImage: '/images/profile1.png',
    favorites: ['movie1', 'movie2'],
    collections: ['collection1', 'collection2'],
  },
  {
    _id: 'profile2',
    user: ['user2'],
    profileImage: '/images/profile2.png',
    favorites: ['movie3', 'movie4'],
    collections: ['collection3', 'collection4'],
  },
  {
    _id: 'profile3',
    user: ['user3'],
    profileImage: '/images/profile3.png',
    favorites: ['movie5', 'movie6'],
    collections: ['collection5', 'collection6'],
  },
  {
    _id: 'profile4',
    user: ['user4'],
    profileImage: '/images/profile4.png',
    favorites: ['movie7', 'movie8'],
    collections: ['collection7', 'collection8'],
  },
  {
    _id: 'profile5',
    user: ['user5'],
    profileImage: '/images/profile5.png',
    favorites: ['movie9', 'movie10'],
    collections: ['collection9', 'collection10'],
  },
  {
    _id: 'profile6',
    user: ['user6'],
    profileImage: '/images/profile6.png',
    favorites: ['movie1', 'movie3'],
    collections: ['collection1', 'collection3'],
  },
  {
    _id: 'profile7',
    user: ['user7'],
    profileImage: '/images/profile7.png',
    favorites: ['movie2', 'movie4'],
    collections: ['collection2', 'collection4'],
  },
  {
    _id: 'profile8',
    user: ['user8'],
    profileImage: '/images/profile8.png',
    favorites: ['movie5', 'movie7'],
    collections: ['collection5', 'collection7'],
  },
  {
    _id: 'profile9',
    user: ['user9'],
    profileImage: '/images/profile9.png',
    favorites: ['movie6', 'movie8'],
    collections: ['collection6', 'collection8'],
  },
  {
    _id: 'profile10',
    user: ['user10'],
    profileImage: '/images/profile10.png',
    favorites: ['movie9', 'movie10'],
    collections: ['collection9', 'collection10'],
  },
];
