export default [
  {
    _id: 'review1',
    type: 'SHORT',
    author: ['user1'],
    movie: ['movie1'],
    rating: 8,
    text: 'Great movie with an engaging storyline!',
    watch_date: new Date('2023-01-10'),
    review_date: new Date('2023-01-15'),
  },
  {
    _id: 'review2',
    type: 'LONG',
    author: ['user2'],
    movie: ['movie2'],
    rating: 7,
    text: 'The cinematography was stunning, but the plot was a bit lacking.',
    watch_date: new Date('2023-02-05'),
    review_date: new Date('2023-02-10'),
  },
  {
    _id: 'review3',
    type: 'SHORT',
    author: ['user3'],
    movie: ['movie3'],
    rating: 9,
    text: 'An absolute masterpiece! Highly recommended.',
    watch_date: new Date('2023-03-12'),
    review_date: new Date('2023-03-15'),
  },
  {
    _id: 'review4',
    type: 'LONG',
    author: ['user4'],
    movie: ['movie4'],
    rating: 5,
    text: 'Despite the hype, I found it to be quite underwhelming.',
    watch_date: new Date('2023-04-18'),
    review_date: new Date('2023-04-20'),
  },
  {
    _id: 'review5',
    type: 'SHORT',
    author: ['user5'],
    movie: ['movie5'],
    rating: 8,
    text: 'A must-watch for anyone who loves action films.',
    watch_date: new Date('2023-05-14'),
    review_date: new Date('2023-05-16'),
  },
  {
    _id: 'review6',
    type: 'LONG',
    author: ['user6'],
    movie: ['movie6'],
    rating: 6,
    text: 'Good visuals, but the story could have been better.',
    watch_date: new Date('2023-06-10'),
    review_date: new Date('2023-06-12'),
  },
  {
    _id: 'review7',
    type: 'SHORT',
    author: ['user7'],
    movie: ['movie7'],
    rating: 9,
    text: 'An emotional rollercoaster. Brilliantly done.',
    watch_date: new Date('2023-07-08'),
    review_date: new Date('2023-07-10'),
  },
  {
    _id: 'review8',
    type: 'LONG',
    author: ['user8'],
    movie: ['movie8'],
    rating: 7,
    text: 'Interesting plot twists, but the pacing was slow.',
    watch_date: new Date('2023-08-15'),
    review_date: new Date('2023-08-17'),
  },
  {
    _id: 'review9',
    type: 'SHORT',
    author: ['user9'],
    movie: ['movie9'],
    rating: 8,
    text: 'A well-crafted story with memorable characters.',
    watch_date: new Date('2023-09-20'),
    review_date: new Date('2023-09-22'),
  },
  {
    _id: 'review10',
    type: 'LONG',
    author: ['user10'],
    movie: ['movie10'],
    rating: 6,
    text: 'Not as good as the original, but still worth a watch.',
    watch_date: new Date('2023-10-25'),
    review_date: new Date('2023-10-27'),
  },
];
