export default [
  {
    _id: 'user1',
    role: 'VIEWER',
    avatar: 'https://avatar.iran.liara.run/public/57',
    name: 'nanabanana',
    password: 'password123',
    reputation: 10,
    join_date: new Date('2023-01-01'),
  },
  {
    _id: 'user2',
    role: 'CRITIC',
    name: 'moviebuff99',
    password: 'password123',
    reputation: 200,
    join_date: new Date('2023-02-01'),
  },
  {
    _id: 'user3',
    role: 'VIEWER',
    name: 'cinemalover',
    password: 'password123',
    reputation: 50,
    join_date: new Date('2023-03-01'),
  },
  {
    _id: 'user4',
    role: 'ADMIN',
    name: 'adminuser',
    password: 'password123',
    reputation: 500,
    join_date: new Date('2023-04-01'),
  },
  {
    _id: 'user5',
    role: 'VIEWER',
    name: 'moviemaniac',
    password: 'password123',
    reputation: 75,
    join_date: new Date('2023-05-01'),
  },
  {
    _id: 'user6',
    role: 'CRITIC',
    name: 'filmcritic',
    password: 'password123',
    reputation: 150,
    join_date: new Date('2023-06-01'),
  },
  {
    _id: 'user7',
    role: 'VIEWER',
    name: 'cinephile',
    password: 'password123',
    reputation: 30,
    join_date: new Date('2023-07-01'),
  },
  {
    _id: 'user8',
    role: 'VIEWER',
    name: 'moviefanatic',
    password: 'password123',
    reputation: 40,
    join_date: new Date('2023-08-01'),
  },
  {
    _id: 'user9',
    role: 'ADMIN',
    name: 'superadmin',
    password: 'password123',
    reputation: 600,
    join_date: new Date('2023-09-01'),
  },
  {
    _id: 'user10',
    role: 'VIEWER',
    name: 'flickfan',
    password: 'password123',
    reputation: 20,
    join_date: new Date('2023-10-01'),
  },
];
